# Generated by Django 3.0.5 on 2020-05-12 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('privelege', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('matricule_id', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipement', models.CharField(max_length=60)),
                ('qte_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fourniseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('materiel_demander', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_panne', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('type_tech', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], default=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('equipement', models.ManyToManyField(to='globals.Equipement')),
                ('type_panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Panne')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='panne',
            field=models.ManyToManyField(to='globals.Panne'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('QTE', models.IntegerField()),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Equipement')),
                ('fourniseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Fourniseur')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('date_resolution', models.DateField()),
                ('Inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Intervention')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Technicien')),
            ],
        ),
    ]
