# Generated by Django 2.0 on 2020-06-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('privelege', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('date_resolution', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('matricule_id', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('QTE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipement', models.CharField(max_length=60)),
                ('qte_stock', models.IntegerField()),
                ('prix_equipement', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(default=0, max_length=30)),
                ('date_facturation', models.DateField(auto_now_add=True)),
                ('clients', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Fourniseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('materiel_demander', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_intervention', models.TextField(max_length=255)),
                ('date_intervention', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medial/%Y/%m/%D')),
                ('latitude', models.FloatField(default=True)),
                ('longtude', models.FloatField(default=True)),
                ('fulladresses', models.TextField(default=True, max_length=500)),
                ('date_fin', models.TextField(default=False, max_length=255)),
                ('durée_mission', models.TextField(default=False, max_length=255)),
                ('clients', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Client')),
                ('equipements', models.ManyToManyField(to='globals.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_panne', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('types', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], default=True, max_length=100)),
                ('disponibilité', models.CharField(default=0, max_length=100)),
                ('specialité', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Panne')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(default=False, max_length=255)),
                ('sujets', models.TextField(default=False, max_length=255)),
                ('priorité', models.TextField(default=False, max_length=255)),
                ('description', models.TextField(default=False, max_length=255)),
                ('etat', models.CharField(default=0, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medial/ticket/%Y/%m/%D')),
                ('clients', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Client')),
                ('intervention', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Intervention')),
            ],
        ),
        migrations.AddField(
            model_name='intervention',
            name='type_panne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Panne'),
        ),
        migrations.AddField(
            model_name='facturation',
            name='interventions',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Intervention'),
        ),
        migrations.AddField(
            model_name='commande',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Equipement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='fourniseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Fourniseur'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='Inter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Intervention'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Technicien'),
        ),
    ]
