# Generated by Django 2.0 on 2020-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='latitude',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='longtude',
            field=models.TextField(max_length=1000),
        ),
    ]
