# Generated by Django 3.0.5 on 2020-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='commentaire',
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='types',
            field=models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], default=True, max_length=100),
        ),
    ]
