# Generated by Django 3.0.5 on 2020-05-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='QTE',
            field=models.IntegerField(null=True),
        ),
    ]
