# Generated by Django 2.0 on 2020-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='location',
        ),
        migrations.AddField(
            model_name='intervention',
            name='latitude',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='longtude',
            field=models.FloatField(default=True),
        ),
    ]
