# Generated by Django 2.0 on 2020-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20200623_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='latitude',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='longtude',
            field=models.FloatField(default=True),
        ),
    ]
