# Generated by Django 2.0 on 2020-06-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20200601_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='equipement',
            new_name='equipements',
        ),
    ]
