# Generated by Django 3.0.5 on 2020-05-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20200511_1735'),
        ('globals', '0002_auto_20200511_1820'),
    ]

    operations = [
    ]
