# Generated by Django 2.0 on 2020-06-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_intervention_fulladresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_fin',
            field=models.TextField(default=True, max_length=255),
        ),
    ]
