# Generated by Django 3.0.5 on 2020-05-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_merge_20200511_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='type_tech',
            field=models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], max_length=60, null=True),
        ),
    ]
