# Generated by Django 2.0 on 2020-06-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_auto_20200602_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='clients',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Client'),
        ),
    ]
