# Generated by Django 2.0 on 2020-06-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_intervention_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_fin',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='disponibilité',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
