# Generated by Django 2.0 on 2020-06-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_intervention_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='specialité',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Panne'),
        ),
    ]
