# Generated by Django 2.0 on 2020-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_auto_20200623_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='priorité',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_priorité', models.TextField(default=False, max_length=255)),
                ('delai', models.TextField(default=False, max_length=255)),
            ],
        ),
    ]
