# Generated by Django 2.0 on 2020-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_auto_20200611_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_fin',
            field=models.TextField(default=False, max_length=255),
        ),
    ]
