# Generated by Django 2.0 on 2020-06-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_technicien_specialité'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='disponibilité',
            field=models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], default=True, max_length=100),
        ),
    ]
