# Generated by Django 2.0 on 2020-06-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_priorité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priorité',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Priorité'),
        ),
    ]
