# Generated by Django 2.0 on 2020-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_technicien_disponibilité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='disponibilité',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
