# Generated by Django 2.0 on 2020-06-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20200611_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='durée_mission',
            field=models.TextField(default=False, max_length=255),
        ),
    ]
