# Generated by Django 2.0 on 2020-06-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0006_auto_20200624_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QTE', models.IntegerField()),
                ('equipements', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='globals.Equipement')),
                ('interventions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.Intervention')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priorité',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
