# Generated by Django 2.0 on 2020-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_auto_20200604_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='date_resolution',
            field=models.DateField(null=True),
        ),
    ]
