# Generated by Django 2.0 on 2020-06-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0007_auto_20200624_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_equipement',
            name='QTE',
            field=models.IntegerField(default=True),
        ),
    ]
