# Generated by Django 2.0 on 2020-05-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('privelege', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(auto_now_add=True)),
                ('date_resolution', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('matricule_id', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('QTE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipement', models.CharField(max_length=60)),
                ('qte_stock', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fourniseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('materiel_demander', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('equipement', models.ManyToManyField(to='global.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_panne', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32)),
                ('typique', models.BooleanField(default=False)),
                ('societe', models.CharField(max_length=60)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.Intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='type_panne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.Panne'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='panne',
            field=models.ManyToManyField(to='global.Panne'),
        ),
        migrations.AddField(
            model_name='commande',
            name='equipement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.Equipement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='fourniseur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.Fourniseur'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='Inter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.Intervention'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='tech_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.Technicien'),
        ),
    ]
