# Generated by Django 2.0 on 2020-05-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affectation',
            old_name='Inter_id',
            new_name='Inter',
        ),
        migrations.RenameField(
            model_name='affectation',
            old_name='tech_id',
            new_name='tech',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='equipement_id',
            new_name='equipement',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='fourniseur_id',
            new_name='fourniseur',
        ),
    ]
