# Generated by Django 3.0.5 on 2020-05-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='technicien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomprenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=10)),
                ('specialité', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.specialite')),
            ],
        ),
    ]
