# Generated by Django 2.0 on 2020-05-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='specialité',
        ),
        migrations.DeleteModel(
            name='specialite',
        ),
        migrations.DeleteModel(
            name='technicien',
        ),
    ]
